language: python
sudo: false
matrix:
    include:
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38
install:
  - pip install tox-travis coveralls
script:
  - tox
notifications:
    email: false
after_success:
  - coveralls
